spring.application.name=activityservice
server.port=${SERVER_PORT:8080}

# MongoDB
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=fitnessdb

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.queue.name=activity.queue
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.completed

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.instance-id=${spring.application.name}:${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=80
eureka.instance.non-secure-port-enabled=true
