spring.application.name=aiservice
server.port=${SERVER_PORT:8084}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.queue.name=activity.queue
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.completed

# Gemini
gemini.api.base-url=${GEMINI_API_BASE_URL}
gemini.api.key=${GEMINI_API_KEY}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=false
