spring.application.name=waterservice
server.port=${PORT:8080}

# MongoDB
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=fitnessdb

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG
logging.level.org.mongodb.driver=DEBUG

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port=443
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.status-page-url=https://${EUREKA_INSTANCE_HOSTNAME}/actuator/info
eureka.instance.health-check-url=https://${EUREKA_INSTANCE_HOSTNAME}/actuator/health
eureka.instance.home-page-url=https://${EUREKA_INSTANCE_HOSTNAME}/


