spring.application.name=waterservice
server.port=${PORT:8085}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=false
